# Change these first
owner: betagouv # Your GitHub username
repo: statut.api.gouv.fr # Your GitHub repository name

# Add your sites here
sites:
  - name: API Particulier
    url: https://particulier.api.gouv.fr/api/ping
  - name: API Adresse (Base Adresse Nationale)
    url: https://api-adresse.data.gouv.fr/search/?q=8+bd+du+port
  - name: API Découpage Administratif - (API Geo)
    url: https://geo.api.gouv.fr/communes/37000?fields=nom,code,codesPostaux,codeDepartement,codeRegion,population&format=json&geometry=centre
  - name: API Aide financieres de l’ADEME
    url: https://koumoul.com/s/data-fair/api/v1/datasets/les-aides-financieres-de-l%27ademe/data-files
  - name: API Aides financières à la rénovation énergetique (Simul’Aid€s)
    url: https://koumoul.com/s/data-fair/api/v1/datasets/simul%27aideuros-dispositifs/data-files
  - name: API Base Carbone
    url: https://koumoul.com/s/data-fair/api/v1/datasets/base-carbone(r)/data-files
  - name: API BOAMP
    url: https://api.dila.fr/opendata/api-boamp/annonces/search?criterion=test
  - name: API Camino
    url: https://api.camino.beta.gouv.fr/titres
  - name: API Répertoire National des Associations
    url: https://entreprise.data.gouv.fr/api/rna/v1/id/W9C1000188
  - name: API Sirene données ouvertes
    url: https://entreprise.data.gouv.fr/api/sirene/v3/etablissements/?etat_administratif=A&siren=345184428
  - name: API Annuaire des établissements publics de l'administration
    url: https://etablissements-publics.api.gouv.fr/v3/departements/35/ccas
  - name: API Répertoire National des Métiers
    url: https://api-rnm.artisanat.fr/v2/entreprises/345184428
  - name: API Jours fériés en France
    url: https://calendrier.api.gouv.fr/jours-feries/metropole.json
  - name: API DILA - Légifrance Beta
    url: https://api.aife.economie.gouv.fr/dila/legifrance-beta/lf-engine-app/consult/ping
  - name: Openfisca-France Web API
    url: https://fr.openfisca.org/api/latest/variable/en_couple
  - name: Transport.data.gouv.fr API
    url: https://transport.data.gouv.fr/api/aoms?lon=2.3522&lat=48.8566

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: statut.api.gouv.fr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://api.gouv.fr/images/api-logo/dinum.png
  name: api.gouv.fr - Disponiblité des API du service public français
  introTitle: "Disponiblité des API du service public"
  introMessage: Retrouvez sur ce tableau de bord, les disponibilités des API d'api.gouv.fr
  navbar:
    - title: Disponibilité
      href: /
    - title: api.gouv.fr
      href: https://api.gouv.fr
    - title: Documentation
      href: https://api.gouv.fr/documentation
    - title: Ajouter une API
      href: https://github.com/betagouv/status.api.gouv.fr/issues
  favicon: https://api.gouv.fr/favicon.ico

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Incidents en cours
  allSystemsOperational: Tous les sytèmes sont opérationnels
  incidentReport: "Rapport d'incident #$NUMBER →"
  activeIncidentSummary: Ouvert le $DATE avec $POSTS posts
  incidentTitle: Détails de l'incident $NUMBER
  incidentDetails: Détails de l'incident
  incidentFixed: Résolu
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert le
  incidentClosedAt: Fermé le
  incidentSubscribe: S'abonner aux mises à jour
  incidentViewOnGitHub: Voir sur GitHub
  incidentCommentSummary: Posté le $DATE par $AUTHOR
  incidentBack: ← Retour aux incidents
  pastIncidents: Incidents passés
  pastIncidentsResolved: Resolu en $MINUTES minutes avec $POSTS posts
  liveStatus: Statut temps réel
  overallUptime: "Disponibilité globale : $UPTIME"
  overallUptimeTitle: Disponibilité globale
  averageResponseTime: "Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Temps de réponse moyen
  sevelDayResponseTime: Temps de réponse sur 7 jours
  responseTimeMs: Temps de réponse (ms)
  up: Opérationnel
  down: Indisponible
  degraded: Dégradé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  footer: Cette page est [open source]($REPO), propulsée par [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Quota dépassé
  rateLimitExceededIntro: Vous avez dépassé le nombre de requêtes que vous pouvez faire en une heure, vous devez donc attendre avant de pouvoir accéder à nouveau au site. Vous pouvez également ajouter un GitHub Personal Access Token pour continuer à utiliser le site.
  rateLimitExceededWhatDoesErrorMean: Que veut dire cette erreur ?
  rateLimitExceededErrorMeaning: Ce site utilise l'API  de Github pour accéder au statut de notre API. Par défaut, Github autorise 60 requêtes par heure par IP, quota que vous avez dépassé.
  rateLimitExceededErrorHowCanFix: Comment réparer cela ?
  rateLimitExceededErrorFix: Vous pouvez attendre l'heure suivante et votre adresse IP sera débloquée. Vous pouvez également renseigner un GitHub Personal Access Token, qui vous donnera un nouveau quota de 5000 requêtes par heure.
  rateLimitExceededGeneratePAT: Voir comment générer un Personal Access Token
  rateLimitExceededHasSet: Vous avez un Personal Access Token renseigné.
  rateLimitExceededRemoveToken: Supprimer le token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copier/coller le token
  rateLimitExceededSaveToken: Enregistrer le token
  errorTitle: Une erreur s'est produite
  errorIntro: Oups ! Une erreur s'est produite en tentant de charger les derniers statuts de disponibilité.
  errorText: Veuillez réessayer dans quelques instants.
  errorHome: Retour à l'accueil
